# Docker Build
#
# 本工作流自动化构建、测试、扫描 Docker 镜像，支持多架构和安全基线检查。
#
# 支持主分支、开发分支、PR、手动触发和定时触发（可解注释 schedule）。

name: Docker Build

on:
  # push:
  #   branches: [ main, develop ]
  #   paths:
  #     - 'Dockerfile'
  #     - 'tcp-forwarder/**'
  #     - '.github/workflows/docker.yml'
  # pull_request:
  #   branches: [ main ]
  #   paths:
  #     - 'Dockerfile'
  #     - 'tcp-forwarder/**'
  # schedule:
  #   - cron: '0 6 * * 1' # 每周构建一次以获取基础镜像更新
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # 1. 构建并推送 Docker 镜像
  build:
    name: 构建并推送 Docker 镜像
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录容器仓库
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 提取镜像元数据
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-,format=short
            type=raw,value=latest,enable={{is_default_branch}}

      - name: 构建并推送 Docker 镜像
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=Rust TCP智能转发器

      - name: Trivy 镜像漏洞扫描
        uses: aquasecurity/trivy-action@master
        if: github.event_name != 'pull_request'
        with:
          image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: 上传 Trivy 扫描结果到 GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        if: always() && github.event_name != 'pull_request'
        with:
          sarif_file: 'trivy-results.sarif'

      - name: 测试 Docker 镜像启动
        if: github.event_name != 'pull_request'
        run: |
          docker run --rm -d --name test-container \
            -p 19234:1234 -p 19099:9099 \
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          sleep 10
          if docker ps | grep test-container; then
            echo "✅ Container started successfully"
            docker logs test-container
          else
            echo "❌ Container failed to start"
            docker logs test-container
            exit 1
          fi
          docker stop test-container

  # 2. 多架构测试（QEMU）
  test-platforms:
    name: 多架构测试 ${{ matrix.platform }}
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 QEMU
        uses: docker/setup-qemu-action@v3

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 构建并测试镜像 ${{ matrix.platform }}
        run: |
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --load \
            -t tcp-forwarder:test-${{ strategy.job-index }} \
            .
          docker run --rm tcp-forwarder:test-${{ strategy.job-index }} --help

  # 3. 安全基线扫描（Dockerfile）
  security-baseline:
    name: Dockerfile 安全基线扫描
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 运行 Checkov 扫描
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: dockerfile
          output_format: sarif
          output_file_path: checkov-results.sarif

      - name: 上传 Checkov 扫描结果
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: checkov-results.sarif

      - name: 运行 Hadolint 扫描
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          format: sarif
          output-file: hadolint-results.sarif

      - name: 上传 Hadolint 扫描结果
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: hadolint-results.sarif
